# nodes/verifier.py
from core.state import AgentState


def verifier_node(state: AgentState) -> dict:
    """
    Verifies that the generated OCI code plan is valid by checking Python syntax.
    On failure, it increments the retry counter and routes to the presentation node for user feedback.
    On success, it routes to the executor.
    """
    print("=" * 60)
    print("✅ VERIFIER NODE - STARTING")
    print("=" * 60)

    plan = state.get("plan")
    if not plan:
        return {
            "plan_valid": False,
            "critique": "No plan was generated by the planner.",
            "next_step": "presentation_node",
            "last_node": "verifier"
        }

    oci_code = plan.get("oci_code")
    if not oci_code:
        return {
            "plan_valid": False,
            "critique": "The plan is missing the 'oci_code' to execute.",
            "next_step": "presentation_node",
            "last_node": "verifier"
        }

    # Increment retries on each verification attempt
    retries = state.get("verify_retries", 0) + 1

    # SIMPLE VALIDATION: Just check for basic Python syntax issues
    try:
        compile(oci_code, '<string>', 'exec')
        print("✅ Plan syntax is valid.")
        
        # Check if plan requires confirmation before execution
        requires_confirmation = plan.get("requires_confirmation", False)
        safety_tier = plan.get("safety_tier", "safe")
        
        if requires_confirmation or safety_tier == "destructive":
            print("⚠️ Plan requires confirmation before execution")
            return {
                "plan_valid": True,
                "critique": None,
                "verify_retries": 0,  # Reset on success
                "next_step": "presentation_node",  # Ask for confirmation
                "confirmation_required": True,  # Set confirmation flag
                "pending_plan": plan,  # Pass the plan for confirmation
                "last_node": "verifier"
            }
        else:
            print("✅ Plan safe to execute directly")
            return {
                "plan_valid": True,
                "critique": None,
                "verify_retries": 0,  # Reset on success
                "next_step": "executor",  # Execute directly
                "last_node": "verifier"
            }
    except SyntaxError as e:
        critique = f"Generated code has a syntax error: {e}"
        print(f"❌ Plan verification failed: {critique}")
        # On failure, update retries and route to presentation node
        return {
            "plan_valid": False,
            "critique": critique,
            "verify_retries": retries,
            "next_step": "presentation_node",
            "last_node": "verifier"
        }
    finally:
        print("=" * 60)
        print("✅ VERIFIER NODE - COMPLETED")
        print("=" * 60)
